# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5610bd39ef4914b3ba3a18b4d4b2f05ce84a6711aea264fc227aa689d0b9aa6c8cf68d26f83fa61fef907292165796ba4566c1807c64d6365e2471b0f6e3a6e9

test:
  secret_key_base: 65bc2e5356e42937a840683739fad9c4131aabf88ed2c0cebc1ca36cb95e695ef91a277dd57662f312303861c3b232455fd5a571b356b753f441ba03d033ae03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
